instrument: [net/, drivers/net/]
config:
 EPOLL: y
 # net/protocols
 PACKET: y
 PACKET_DIAG: y
 UNIX: y
 UNIX_DIAG: y
 XFRM_USER: y
 XFRM_SUB_POLICY: y
 XFRM_MIGRATE: y
 NET_KEY: y
 NET_KEY_MIGRATE: y
 INET: y
 INET_DIAG: y
 INET_UDP_DIAG: y
 IPV6: y
 IP_DCCP: y
 IP_SCTP: y
 RDS: y
 RDS_TCP: y
 RDS_DEBUG: n
 TIPC: y
 TIPC_MEDIA_UDP: y
 ATM: y
 L2TP: y
 L2TP_V3: y
 L2TP_IP: y
 DECNET: y
 DECNET_ROUTER: y
 LLC2: y
 IPX: y
 ATALK: y
 X25: y
 LAPB: y
 PHONET: y
 HAMRADIO: y
 CAN: y
 CAN_RAW: y
 CAN_BCM: y
 CAN_GW: y
 CAN_DEV: y
 IRDA: y
 BT: y
 BT_RFCOMM: y
 AF_RXRPC: y
 AF_RXRPC_DEBUG: n
 CAIF: y
 CAIF_DEBUG: n
