instrument: [fs/btrfs/]
config:
 BLK_DEV_LOOP: y
 BLK_DEV_LOOP_MIN_COUNT: 8
 BTRFS_FS: y
 BTRFS_FS_POSIX_ACL: y
 BTRFS_FS_CHECK_INTEGRITY: y
 BTRFS_FS_RUN_SANITY_TESTS: n
 BTRFS_DEBUG: n
 BTRFS_ASSERT: y
