# UML doesn't support USB drivers, unfortunately
vm: kvm
instrument:
 - drivers/usb/
 - drivers/net/
 - drivers/media/
 - drivers/hid/
 - drivers/staging/
 - sound/usb/
config:
 USB_DUMMY_HCD: y
 USB_GADGET: y
 USB_GADGETFS: y

 # USB support
 USB_ANNOUNCE_NEW_DEVICES: y
 USB_DEFAULT_PERSIST: y
 USB_DYNAMIC_MINORS: y
 USB_OTG_WHITELIST: n
 USB_OTG_BLACKLIST_HUB: n
 USB_ULPI_BUS: y
 USB_MON: n
 USB_WUSB: y
 USB_WUSB_CBAF: y
 USB_WUSB_CBAF_DEBUG: n
 USB_U132_HCD: y
 #USB_RENESAS_USBHS_HCD: y
 USB_HWA_HCD: y
 USB_HCD_TEST_MODE: n
 #USB_RENESAS_USBHS: y
 USB_ACM: y
 USB_PRINTER: y
 USB_WDM: y
 USB_TMC: y
 USB_STORAGE: y
 USB_STORAGE_DEBUG: n
 USB_STORAGE_REALTEK: y
 USB_STORAGE_DATAFAB: y
 USB_STORAGE_FREECOM: y
 USB_STORAGE_ISD200: y
 USB_STORAGE_USBAT: y
 USB_STORAGE_SDDR09: y
 USB_STORAGE_SDDR55: y
 USB_STORAGE_JUMPSHOT: y
 USB_STORAGE_ALAUDA: y
 USB_STORAGE_KARMA: y
 USB_STORAGE_CYPRESS_ATACB: y
 USB_STORAGE_ENE_UB6250: y
 USB_UAS: y
 USB_MDC800: y
 USB_MICROTEK: y
 USBIP_CORE: y
 USBIP_VHCI_HCD: y
 USBIP_HOST: y
 USBIP_DEBUG: n
 USB_ISP1760: y
 USB_ISP1760_DUAL_ROLE: y
 USB_SERIAL: y
 USB_SERIAL_CONSOLE: y
 USB_SERIAL_GENERIC: y
 USB_SERIAL_SIMPLE: y
 USB_SERIAL_AIRCABLE: y
 USB_SERIAL_ARK3116: y
 USB_SERIAL_BELKIN: y
 USB_SERIAL_CH341: y
 USB_SERIAL_WHITEHEAT: y
 USB_SERIAL_DIGI_ACCELEPORT: y
 USB_SERIAL_CP210X: y
 USB_SERIAL_CYPRESS_M8: y
 USB_SERIAL_EMPEG: y
 USB_SERIAL_FTDI_SIO: y
 USB_SERIAL_VISOR: y
 USB_SERIAL_IPAQ: y
 USB_SERIAL_IR: y
 USB_SERIAL_EDGEPORT: y
 USB_SERIAL_EDGEPORT_TI: y
 USB_SERIAL_F81232: y
 USB_SERIAL_GARMIN: y
 USB_SERIAL_IPW: y
 USB_SERIAL_IUU: y
 USB_SERIAL_KEYSPAN_PDA: y
 USB_SERIAL_KEYSPAN: y
 USB_SERIAL_KLSI: y
 USB_SERIAL_KOBIL_SCT: y
 USB_SERIAL_MCT_U232: y
 USB_SERIAL_METRO: y
 USB_SERIAL_MOS7720: y
 USB_SERIAL_MOS7840: y
 USB_SERIAL_MXUPORT11: y
 USB_SERIAL_MXUPORT: y
 USB_SERIAL_NAVMAN: y
 USB_SERIAL_PL2303: y
 USB_SERIAL_OTI6858: y
 USB_SERIAL_QCAUX: y
 USB_SERIAL_QUALCOMM: y
 USB_SERIAL_SPCP8X5: y
 USB_SERIAL_SAFE: y
 USB_SERIAL_SAFE_PADDED: y
 USB_SERIAL_SIERRAWIRELESS: y
 USB_SERIAL_SYMBOL: y
 USB_SERIAL_TI: y
 USB_SERIAL_CYBERJACK: y
 USB_SERIAL_XIRCOM: y
 USB_SERIAL_OPTION: y
 USB_SERIAL_OMNINET: y
 USB_SERIAL_OPTICON: y
 USB_SERIAL_XSENS_MT: y
 USB_SERIAL_WISHBONE: y
 USB_SERIAL_SSU100: y
 USB_SERIAL_QT2: y
 USB_SERIAL_DEBUG: y
 USB_EMI62: y
 USB_EMI26: y
 USB_ADUTUX: y
 USB_SEVSEG: y
 USB_RIO500: y
 USB_LEGOTOWER: y
 USB_LCD: y
 USB_LED: y
 USB_CYPRESS_CY7C63: y
 USB_CYTHERM: y
 USB_IDMOUSE: y
 USB_FTDI_ELAN: y
 USB_LD: y
 USB_TRANCEVIBRATOR: y
 USB_IOWARRIOR: y
 USB_TEST: n
 USB_EHSET_TEST_FIXTURE: y
 USB_ISIGHTFW: y
 USB_YUREX: y
 USB_EZUSB_FX2: y
 USB_HSIC_USB3503: y
 USB_LINK_LAYER_TEST: n
 USB_CHAOSKEY: y
 USB_ATM: y
 USB_SPEEDTOUCH: y
 USB_CXACRU: y
 USB_UEAGLEATM: y
 USB_XUSBATM: y
 #KEYSTONE_USB_PHY: y
 NOP_USB_XCEIV: y
 #AM335X_PHY_USB: y
 USB_GPIO_VBUS: y
 USB_ISP1301: y
 #USB_MSM_OTG: y
 #USB_QCOM_8X16_PHY: y
 USB_LED_TRIG: y

 # USB sound devices
 SND_USB: y
 SND_USB_AUDIO: y
 SND_USB_UA101: y
 SND_USB_USX2Y: y
 SND_USB_CAIAQ: y
 SND_USB_CAIAQ_INPUT: y
 SND_USB_US122L: y
 SND_USB_6FIRE: y
 SND_USB_HIFACE: y
 SND_BCD2000: y
 SND_USB_POD: y
 SND_USB_PODHD: y
 SND_USB_TONEPORT: y
 SND_USB_VARIAX: y

 # Media USB Adapters
 USB_VIDEO_CLASS: y
 USB_VIDEO_CLASS_INPUT_EVDEV: y
 USB_GSPCA: y
 USB_M5602: y
 USB_STV06XX: y
 USB_GL860: y
 USB_GSPCA_BENQ: y
 USB_GSPCA_CONEX: y
 USB_GSPCA_CPIA1: y
 USB_GSPCA_DTCS033: y
 USB_GSPCA_ETOMS: y
 USB_GSPCA_FINEPIX: y
 USB_GSPCA_JEILINJ: y
 USB_GSPCA_JL2005BCD: y
 USB_GSPCA_KINECT: y
 USB_GSPCA_KONICA: y
 USB_GSPCA_MARS: y
 USB_GSPCA_MR97310A: y
 USB_GSPCA_NW80X: y
 USB_GSPCA_OV519: y
 USB_GSPCA_OV534: y
 USB_GSPCA_OV534_9: y
 USB_GSPCA_PAC207: y
 USB_GSPCA_PAC7302: y
 USB_GSPCA_PAC7311: y
 USB_GSPCA_SE401: y
 USB_GSPCA_SN9C2028: y
 USB_GSPCA_SN9C20X: y
 USB_GSPCA_SONIXB: y
 USB_GSPCA_SONIXJ: y
 USB_GSPCA_SPCA500: y
 USB_GSPCA_SPCA501: y
 USB_GSPCA_SPCA505: y
 USB_GSPCA_SPCA506: y
 USB_GSPCA_SPCA508: y
 USB_GSPCA_SPCA561: y
 USB_GSPCA_SPCA1528: y
 USB_GSPCA_SQ905: y
 USB_GSPCA_SQ905C: y
 USB_GSPCA_SQ930X: y
 USB_GSPCA_STK014: y
 USB_GSPCA_STK1135: y
 USB_GSPCA_STV0680: y
 USB_GSPCA_SUNPLUS: y
 USB_GSPCA_T613: y
 USB_GSPCA_TOPRO: y
 USB_GSPCA_TOUPTEK: y
 USB_GSPCA_TV8532: y
 USB_GSPCA_VC032X: y
 USB_GSPCA_VICAM: y
 USB_GSPCA_XIRLINK_CIT: y
 USB_GSPCA_ZC3XX: y
 USB_PWC: y
 USB_PWC_DEBUG: n
 USB_PWC_INPUT_EVDEV: y
 VIDEO_CPIA2: y
 USB_ZR364XX: y
 USB_STKWEBCAM: y
 USB_S2255: y
 VIDEO_USBTV: y
 VIDEO_PVRUSB2: y
 VIDEO_PVRUSB2_SYSFS: y
 VIDEO_PVRUSB2_DVB: y
 VIDEO_PVRUSB2_DEBUGIFC: n
 VIDEO_HDPVR: y
 VIDEO_USBVISION: y
 VIDEO_STK1160_COMMON: y
 VIDEO_STK1160_AC97: y
 VIDEO_GO7007: y
 VIDEO_GO7007_USB: y
 VIDEO_GO7007_LOADER: y
 VIDEO_GO7007_USB_S2250_BOARD: y
 VIDEO_AU0828: y
 VIDEO_AU0828_V4L2: y
 VIDEO_AU0828_RC: y
 VIDEO_CX231XX: y
 VIDEO_CX231XX_RC: y
 VIDEO_CX231XX_ALSA: y
 VIDEO_CX231XX_DVB: y
 VIDEO_TM6000: y
 VIDEO_TM6000_ALSA: y
 VIDEO_TM6000_DVB: y
 DVB_USB: y
 DVB_USB_DEBUG: n
 DVB_USB_A800: y
 DVB_USB_DIBUSB_MB: y
 DVB_USB_DIBUSB_MB_FAULTY: y
 DVB_USB_DIBUSB_MC: y
 DVB_USB_DIB0700: y
 DVB_USB_UMT_010: y
 DVB_USB_CXUSB: y
 DVB_USB_M920X: y
 DVB_USB_DIGITV: y
 DVB_USB_VP7045: y
 DVB_USB_VP702X: y
 DVB_USB_GP8PSK: y
 DVB_USB_NOVA_T_USB2: y
 DVB_USB_TTUSB2: y
 DVB_USB_DTT200U: y
 DVB_USB_OPERA1: y
 DVB_USB_AF9005: y
 DVB_USB_AF9005_REMOTE: y
 DVB_USB_PCTV452E: y
 DVB_USB_DW2102: y
 DVB_USB_CINERGY_T2: y
 DVB_USB_DTV5100: y
 DVB_USB_FRIIO: y
 DVB_USB_AZ6027: y
 DVB_USB_TECHNISAT_USB2: y
 DVB_USB_V2: y
 DVB_USB_AF9015: y
 DVB_USB_AF9035: y
 DVB_USB_ANYSEE: y
 DVB_USB_AU6610: y
 DVB_USB_AZ6007: y
 DVB_USB_CE6230: y
 DVB_USB_EC168: y
 DVB_USB_GL861: y
 DVB_USB_LME2510: y
 DVB_USB_MXL111SF: y
 DVB_USB_RTL28XXU: y
 DVB_USB_DVBSKY: y
 DVB_TTUSB_BUDGET: y
 DVB_TTUSB_DEC: y
 SMS_USB_DRV: y
 DVB_B2C2_FLEXCOP_USB: y
 DVB_B2C2_FLEXCOP_USB_DEBUG: n
 DVB_AS102: y
 VIDEO_EM28XX: y
 VIDEO_EM28XX_V4L2: y
 VIDEO_EM28XX_ALSA: y
 VIDEO_EM28XX_DVB: y
 VIDEO_EM28XX_RC: y
 USB_AIRSPY: y
 USB_HACKRF: y

 # USB Network Adapters
 USB_CATC: y
 USB_KAWETH: y
 USB_PEGASUS: y
 USB_RTL8150: y
 USB_RTL8152: y
 USB_LAN78XX: y
 USB_USBNET: y
 USB_NET_AX8817X: y
 USB_NET_AX88179_178A: y
 USB_NET_CDCETHER: y
 USB_NET_CDC_EEM: y
 USB_NET_CDC_NCM: y
 USB_NET_HUAWEI_CDC_NCM: y
 USB_NET_CDC_MBIM: y
 USB_NET_DM9601: y
 USB_NET_SR9700: y
 USB_NET_SR9800: y
 USB_NET_SMSC75XX: y
 USB_NET_SMSC95XX: y
 USB_NET_GL620A: y
 USB_NET_NET1080: y
 USB_NET_PLUSB: y
 USB_NET_MCS7830: y
 USB_NET_RNDIS_HOST: y
 USB_NET_CDC_SUBSET: y
 USB_ALI_M5632: y
 USB_AN2720: y
 USB_BELKIN: y
 USB_ARMLINUX: y
 USB_EPSON2888: y
 USB_KC2190: y
 USB_NET_ZAURUS: y
 USB_NET_CX82310_ETH: y
 USB_NET_KALMIA: y
 USB_NET_QMI_WWAN: y
 USB_HSO: y
 USB_NET_INT51X1: y
 USB_CDC_PHONET: y
 USB_IPHETH: y
 USB_SIERRA_NET: y
 USB_VL600: y
 USB_NET_CH9200: y

 # Misc
 I2C_TINY_USB: y
 IR_IGORPLUGUSB: y
 IR_MCEUSB: y
 IR_TTUSBIR: y
 JOYSTICK_IFORCE_USB: y
 MEMSTICK_REALTEK_USB: y
 MFD_RTSX_USB: y
 MISDN_HFCUSB: y
 MMC_REALTEK_USB: y
 MOUSE_SYNAPTICS_USB: y
 ORINOCO_USB: y
 RT2500USB: y
 RT2800USB: y
 RT2800USB_RT33XX: y
 RT2800USB_RT3573: y
 RT2800USB_RT35XX: y
 RT2800USB_RT53XX: y
 RT2800USB_RT55XX: y
 RT2800USB_UNKNOWN: y
 TABLET_USB_ACECAD: y
 TABLET_USB_AIPTEK: y
 TABLET_USB_GTCO: y
 TABLET_USB_HANWANG: y
 TABLET_USB_KBTAB: y
 TAHVO_USB: y
 TAHVO_USB_HOST_BY_DEFAULT: y
 TOUCHSCREEN_USB_3M: y
 TOUCHSCREEN_USB_COMPOSITE: y
 TOUCHSCREEN_USB_DMC_TSC10: y
 TOUCHSCREEN_USB_E2I: y
 TOUCHSCREEN_USB_EASYTOUCH: y
 TOUCHSCREEN_USB_EGALAX: y
 TOUCHSCREEN_USB_ELO: y
 TOUCHSCREEN_USB_ETT_TC45USB: y
 TOUCHSCREEN_USB_ETURBO: y
 TOUCHSCREEN_USB_GENERAL_TOUCH: y
 TOUCHSCREEN_USB_GOTOP: y
 TOUCHSCREEN_USB_GUNZE: y
 TOUCHSCREEN_USB_IDEALTEK: y
 TOUCHSCREEN_USB_IRTOUCH: y
 TOUCHSCREEN_USB_ITM: y
 TOUCHSCREEN_USB_JASTEC: y
 TOUCHSCREEN_USB_NEXIO: y
 TOUCHSCREEN_USB_PANJIT: y
 TOUCHSCREEN_USB_ZYTRONIC: y
 USB_APPLEDISPLAY: y
 USB_HID: y
 HID_PID: y
 USB_HIDDEV: y
 USB_IDMOUSE: y
 USB_RAREMONO: y
