instrument: [fs/reiserfs/]
config:
 BLK_DEV_LOOP: y
 BLK_DEV_LOOP_MIN_COUNT: 8
 REISERFS_FS: y
 REISERFS_CHECK: n
 REISERFS_PROC_INFO: y
 REISERFS_FS_XATTR: y
 REISERFS_FS_POSIX_ACL: y
 REISERFS_FS_SECURITY: y
