instrument: [fs/ocfs2/]
config:
 BLK_DEV_LOOP: y
 BLK_DEV_LOOP_MIN_COUNT: 8
 OCFS2_FS: y
 OCFS2_FS_O2CB: y
 OCFS2_FS_USERSPACE_CLUSTER: y
 OCFS2_FS_STATS: y
 OCFS2_DEBUG_MASKLOG: n
 OCFS2_DEBUG_FS: n
